samples={
"DY0J"  : {"files":["/scratch/arizzi/giulio/DYJetsToLL_0J_nano2017.root"]},
"DY1J"  : {"files":["/scratch/arizzi/giulio/DYJetsToLL_1J_nano2017.root"]},
"DY2J"  : {"files":["/scratch/arizzi/giulio/DYJetsToLL_2J_nano2017.root"]},
"DYTau" : {"files":["/scratch/arizzi/giulio/DYJetsToTauTau_ForcedMuDecay_nano2017.root"]},
"ggHmm": {"files":["/scratch/arizzi/giulio/GluGluHToMuMu_nano2017.root"]},
"STs" : {"files":["/scratch/arizzi/giulio/ST_s_nano2017.root"]},
"STwtbar": {"files":["/scratch/arizzi/giulio/ST_tW_antitop_nano2017.root"]},
"STwt": {"files":["/scratch/arizzi/giulio/ST_tW_top_nano2017.root"]},
"STtbar": {"files":["/scratch/arizzi/giulio/ST_t_antitop_nano2017.root"]},
"STt": {"files":["/scratch/arizzi/giulio/ST_t_top_nano2017.root"]},
#"data": {"files":["/scratch/arizzi/giulio/SingleMuon_nano2017.root"]},
"TTlep": {"files":["/scratch/arizzi/giulio/TTTo2L2Nu_nano2017.root"]},
"TThad": {"files":["/scratch/arizzi/giulio/TTToHadronic_nano2017.root"]},
"TTsemi": {"files":["/scratch/arizzi/giulio/TTToSemiLeptonic_nano2017.root"]},
"vbfHmm": {"files":["/scratch/arizzi/giulio/VBF_HToMuMu_nano2017.root"]},
"W2J": {"files":["/scratch/arizzi/giulio/WJetsToLNu_2J_nano2017.root"]},
"W0J": {"files":["/scratch/arizzi/giulio/WToLNu_0J_nano2017.root"]},
"WWdps": {"files":["/scratch/arizzi/giulio/WWTo2L2Nu_DoubleScattering_nano2017.root"]},
"WW2l2n": {"files":["/scratch/arizzi/giulio/WWTo2L2Nu_nano2017.root"]},
"WW4q": {"files":["/scratch/arizzi/giulio/WWTo4Q_nano2017.root"]},
"WWlnqq": {"files":["/scratch/arizzi/giulio/WWToLNuQQ_nano2017.root"]},
"WZ1l1n2q": {"files":["/scratch/arizzi/giulio/WZTo1L1Nu2Q_nano2017.root"]},
"WZ1l3n": {"files":["/scratch/arizzi/giulio/WZTo1L3Nu_nano2017.root"]},
"WZ2l2q": {"files":["/scratch/arizzi/giulio/WZTo2L2Q_nano2017.root"]},
"WZ3l1n": {"files":["/scratch/arizzi/giulio/WZTo3LNu_nano2017.root"]},
"WZ": {"files":["/scratch/arizzi/giulio/WZ_nano2017.root"]},
"ZZ2l2n": {"files":["/scratch/arizzi/giulio/ZZTo2L2Nu_nano2017.root"]},
"ZZ2l2q": {"files":["/scratch/arizzi/giulio/ZZTo2L2Q_nano2017.root"]},
"ZZ2q2n": {"files":["/scratch/arizzi/giulio/ZZTo2Q2Nu_nano2017.root"]},
"ZZ4l": {"files":["/scratch/arizzi/giulio/ZZTo4L_nano2017.root"]},
"ZZ": {"files":["/scratch/arizzi/giulio/ZZ_nano2017.root"]},
}
